FORMAT: 1A
HOST: https://apitest.paysafecard.com/v1/reports/settlement

# Paysafecard settlement report API

# Technical introduction
This section provides a technical introduction to the paysafecard settlement report API. 

## About the API
This revue describes the settlement report API for business partners of paysafecard.
The settlement report informs about all successful debited transactions.
The data can be filtered by various criteria. The reports are shown as text-file in csvformat
(Comma-Separated Values).
The internet connection (e.g. through firewall) must allow secured HTTP connections
(HTTPS).
The necessary API KEY will be sent to the business partner upon request.


## Versioning
Every time there is backwards-incompatible change to the API, a new major version will be released. This major version is part of the URL path.
The current major version is *v1*. Unless informed by our technical support department that we are dropping support for a particular API version, you do not need to switch API versions.


## Prerequisites
You can only connect to paysafecard if the following prerequisites are fulfilled:
- API key for request authentification provided by paysafecard.
- Authorisation of the payment server IP address (if a 403 error is received when trying to access the service, it is likely that the IP address is not yet allowed to access).
- Content-type: Please make sure that the content type in the HTTP header, when submitting requests, is set to **Content-Type: application/json**
- Character encoding needs to be in UTF-8

## API key authentication
Every request to the paysafecard API is authenticated using an API key.
- The value of the **API key needs to be base64 encoded** when transmitted in the HTTP header!
- Set the key as the username. [*HTTP basic authentication*](http://en.wikipedia.org/wiki/Basic_access_authentication)
- Your API key may only be used from your backend systems.
- *Please note: Your API key must be kept secured - never expose the API key to anybody!*

Below is an example of how the API key is supposed to be set.

```
Authorization: Basic cHNjX0R4dThqSnI1LVdPYXhLWnpjOXdyMUtNLXd1Y3dZMXg=
```

## Endpoint

- The endpoint for the *production environment* is: https://api.paysafecard.com/v1/reports/settlement

## Generate settlement report

In the debit report only all successfully debited transactions are listed.  
All transactions that are here listed have exclusively status SUCCESS.
In order to reconcile the settlement with the debit report, please use the stated
invoice number in the invoice as a search filter.

### NOTE FOLLOWING LIMITS:

You can only connect to paysafecard if the following prerequisites are fulfilled:
- file download: maximum 200.000 downloadable lines
- maximum allowed search with date filter:3 months at once

## Settlement Report [/reports/settlement?{mid}&{from}&{to}&{reporting_criteria}&{merchant_client_id}&{invoice_number}&{include_header}]

### Retrieve Settlement Report [GET]

+ Parameter

    + mid: 1000000001 (array, optional) - If no mids are present, all mids that are bound to this account will be searched
    + from: `2016-09-20` (string, required) - The from date
    + to: `2016-09-20` (string, required) - The to date
    + `reporting_criteria`: RC1 (string, optional) - The reporting criteria
    + `merchant_client_id`: encryt3d3m4il (string, optional) - The customer id
    + `invoice_number`: INV1 (string, optional) - The invoice number. Required if from and to are missing
    + `include_header`: false (boolean, optional) - If the response should include a header with the csv field names 

+ Request

    + Headers
            
            Authorization: Basic cHNjX0R4dThqSnI1LVdPYXhLWnpjOXdyMUtNLXd1Y3dZMXg=


+ Response 200 (text/csv)

        "1000000433","748112164489","1","4005","","EUR","16.99","6.75",".000","16.99","1.00000","1090603634","9100157020","2016-03-14 23:59:52.109","16.99",".00","15.84","2016-03-14 23:59:18.751","","DE","DE"
        "1000000433","181140558899","1","7484","","EUR","5.00","7.00",".000","5.00","1.00000","1090603634","9100156911","2016-03-14 23:59:47.777","5.00",".00","4.65","2016-03-14 23:55:23.900","","CZ","CZ"
        "1000000433","181140559359","1","7484","","EUR","1.99","7.00",".000","1.99","1.00000","1090603634","9100156917","2016-03-14 23:59:45.902","1.99",".00","1.85","2016-03-14 23:59:26.641","","PT","PT"

# Group Settlement report Error Codes

|Code                           |Number (optional)  |HTTP Status    |Description          |
|---                                                                        |---                |---            |---                  |
|`general_technical_error`                                                  |10007              |500            |General technical error.|
|`invalid_api_key`                                                          |10008              |401            |Authentication failed due to missing or invalid API key. Your key needs to be set to the HTTP auth username.|
|`invalid_request_parameter`                                                |10028              |400            |One of the request parameters failed validation. The `message` and `param` fields contain more detailed information.|
|`duplicate_transaction_id`                                                 |2001               |400            |Transaction already exists.|
|`payment_invalid_state`                                                    |2017               |400            |The payment is in an invalid state, e.g. you tried to capture a payment that is in state `INITIATED` instead of `AUTHORIZED`.|
|`Merchant with Id XXXXXXXXXX is not active.`                               |3001               |400            |Merchant is not active.|
|`Merchant with Id XXXXXXXXXX is not allowed to perform this debit any more`|3007               |400            |Debit attempt after expiry of dispo time window.|
|`submerchant_not_found`                                                    |3014               |400            |The `submerchant_id` specified by you has not been configured.|