FORMAT: 1A
HOST: https://apitest.paysafecard.com/v1

# paysafecard SafetyPay integration

This documentation explains how to start accepting <a href="https://www.safetypay.com/en/">SafetyPay</a> payments. 

It is an add-on to the classic paysafecard integration:


**REST API**: 
<br><br>https://www.paysafecard.com/en/business/downloads/

**SOAP API**: 
<br><br>
https://www.paysafecard.com/en/business/downloads/
<br><br>
https://www.paysafecard.com/fileadmin/api/paysafecardsopg.html

## Group Where to start?
To initiate the process of accepting SafetyPay, the business partner must contact the account manager directly or at [*sales@paysafecard.com*]().
Once the business process is finished, the feature will be activated from paysafecard side. The feature will be activated per MID (Merchant ID).

There are also some technical integration changes necessary, which will be described in detail [here](#technical_changes).

## Introduction
There are alternative payment flows to integrate SafetyPay into your payment ecosystem. In the following section we will describe the general customer flow for each of the alternatives.
<a name="existing_MID"></a>
# Group Payment Process  with intermediary paysafecard redirection

## SafetyPay payment option on the paysafecard Payment Panel

### [Customer Flow](#customer_flows)
1. The customer selects paysafecard/SafetyPay as the preferred payment method at the business partner checkout page
2. The businesss partner initiates the payment with the correct amount, currency and other necessary parameters
3. The customer is redirected to the paysafecard hosted payment panel
4. The customer sees paysafecard and SafetyPay payment option on the payment panel
5. The customer selects SafetyPay and is redirected to the SafetyPay payment page
6. The customer is presented with 2 options to complete their payment: Cash or Online
    * "online" - Flow:
    5. The customer completes the payment with one of the presented online Payment Methods
    6. paysafecard sends a notification to the notification URL once the payment is complete
    7. The business partner captures the payment
    8. The customer may return to the success_url/okURL provided during the payment request. This is optional.
    * "cash" - Flow: 
    5. The customer receives a SafetyPay operation ID and pays for it at a point of collection
    6. paysafecard sends a notification to the notification URL once the payment is complete
    7. The business partner captures the payment

## Cash payment - with paysafecard redirection
[Cash Payment process - REST](#cash_payment_REST_PP)<br>
[Cash Payment process - SOAP](#cash_payment_SOAP_PP)
![Payment Flow](https://www.paysafecard.com/fileadmin/api/images/Diagram_SafetyPay_CASH_PP.jpg)



## Online Payment - with paysafecard redirection
[Online Payment process - REST](#online_payment_REST_PP)<br>
[Online Payment process - SOAP](#cash_payment_SOAP_PP)
![Payment Flow](https://www.paysafecard.com/fileadmin/api/images/Diagram_SafetyPay_ONLINE_PP.jpg)

<a name="separate_MID"></a>
# Group Payment Process with immediate redirection to SafetyPay

##  SafetyPay payment option with immediate redirection to SafetyPay

### [Customer Flow](#customer_flows)
1. The customer selects SafetyPay as the preferred payment method at the business partner checkout page
2. The businesss partner initiates the payment with "payment_instrument" & "payment_instrument_subtype" parameters set
3. The customer is redirected to the SafetyPay hosted payment page
4. The customer is presented with the selected option to complete their payment depening on the "payment_instrument_subtype" set during the request: Cash or Online
    * "online" - Flow:
    5. The customer completes the payment with one of the presented online Payment Methods
    6. paysafecard sends a notification to the notification URL once the payment is complete
    7. The business partner captures the payment
    8. The customer may return to the success_url/okURL provided during the payment request. This is optional.
    * "cash" - Flow: 
    5. The customer receives a SafetyPay operation ID and pays for it at a point of collection
    6. paysafecard sends a notification to the notification URL once the payment is complete
    7. The business partner captures the payment

## Cash payment with immediate redirection to SafetyPay
[Cash Payment process - REST](#cash_payment_REST_noPP)<br>
[Cash Payment process - SOAP](#cash_payment_SOAP_noPP)
![Payment Flow](https://www.paysafecard.com/fileadmin/api/images/Diagram_SafetyPay_CASH_noPP.jpg)




## Online Payment with immediate redirection to SafetyPay
[Cash Payment process - REST](#online_payment_REST_noPP)<br>
[Cash Payment process - SOAP](#online_payment_SOAP_noPP)
![Payment Flow](https://www.paysafecard.com/fileadmin/api/images/Diagram_SafetyPay_ONLINE_noPP.jpg)



# Group Technical changes
<a name="technical_changes"></a>

1. The logo must be changed accordingly at the checkout page 

2. Transactions must stay open for 48 hours before you can consider them incomplete

3. (Optional) The payment must be created accordingly to the choice of the customer at the checkout page. The integrations supports the usage of choosing the Payment Method during the Payment request. See section [Initiating a SafetyPay Payment - REST](#restrictions_REST) or [Creating a SafetyPay Disposition - SOAP](#restrictions_SOPG)
    * [Initiating a SafetyPay Payment - REST](#restrictions_REST)
    * [Creating a SafetyPay Disposition - SOAP](#restrictions_SOPG)
    
4. (Optional) Integrating the payment notification payload in JSON 
    * The [JSON payment notification](#payment_notification) enables the business partner to distinguish which payment instrument subtype was used for the transaction.


# Group Initiating a SafetyPay Payment - REST

<a name="initiate_payment"></a>
## restrictions [/payments]
<a name="restrictions_REST"></a>
The array `restrictions` containing the `payment_instrument`, `payment_instrument_subtype` & `bank_ids` parameters gives the possibility to initiate a payment for the specific option chosen by the customer
at the merchant's checkout. When choosing the `payment_instrument`, the customer will be redirected to the SafetyPay payment page immediately.

| Parameter                     | Type                       | Description      | Possible values
| ---                           | ---                        | ---              | ---                  
| `restrictions`                | Array                      | The payment restrictions array.
| `payment_instrument`          | String                     | The payment instrument gives the possibility to initiate the payment for the specific option chosen at the merchant's checkout page. |`paysafecard`, `safetypay`
| `payment_instrument_subtype`          | String             | The payment instrument subtype gives the possibility to initiate the payment for the specific option chosen at the merchant's checkout page. |`cash`,`online`
| `bank_ids`                    | Numerical Array            | The bank ID restriction gives the possibility to only show certain bank options. It is an array that allows multiple options.    | A list of bank IDs can be found at the bottom under ["Bank IDs"](#bank_ids)

### Initiate Payment Example

```
{
  "type": "PAYSAFECARD",
  "amount": 2000.00,
  "currency": "BRL",
  "redirect": {
    "success_url": "https://www.paysafecard.com/okURL",
    "failure_url": "https://www.paysafecard.com/nokURL"
  },
  "notification_url": "https://www.paysafecard.com/pnUrl",
  "customer": {
    "id": "customer_id2"
  },
  "shop_id":"test123",
    "restrictions": {
    "payment_instrument": "safetypay",
    "payment_instrument_subtype": "online",
    "bank_ids": ["8439"]
  }
}

```

### New Error Code
Error number "2039" indicates that the one of the values passed in `payment_instrument` <!--or `payment_instrument_subtype`,--> is not a valid value.


```
{
    "code": "invalid_restriction",
    "message": "Could not convert restriction value 'giftcard_test'!",
    "number": 2039
}
```

<a name="initiate_payment"></a>
### initiate payment request [POST]

+ Request (application/json)

        Authorization: Basic cHNjX25wZ0g2THkxa3NXMS1CZzBQaURDNGZ0dzliSWtzQkY=

+ Attributes (PaymentRequest)

+ Response 201 (application/json)

            {
            "object": "PAYMENT",
            "id": "pay_1100000000_v2Pa0tDn0tr1CppVkSQ0yjY77eVOO5Pl_USD",
            "created": 1607074107062,
            "updated": 1607074107062,
            "currency": "USD",
            "status": "INITIATED",
            "type": "PAYSAFECARD",
            "redirect": {
            "success_url": "https://ok.com/pay_1100000000_v2Pa0tDn0tr1CppVkSQ0yjY77eVOO5Pl_USD",
            "failure_url": "https://nok.com/pay_1100000000_v2Pa0tDn0tr1CppVkSQ0yjY77eVOO5Pl_USD",
            "auth_url": "https://customer.test.at.paysafecard.com/psccustomer/GetCustomerPanelServlet?mid=1100000000&mtid=pay_1100000000_v2Pa0tDn0tr1CppVkSQ0yjY77eVOO5Pl_USD&amount=1.00&currency=USD"
            },
            "customer": {
            "id": "test_dev"
            }, "restrictions": {
                    "payment_instrument":"safetypay",
                    "payment_instrument_subtype":"cash"
            }
            "amount": 1.00,
            "notification_url": "https://9fc7622ff6a8995a8919be9c134d39a5.m.pipedream.net"
            }







# Group Creating a SafetyPay Disposition - SOAP
<a name="restrictions_SOPG"></a>
The disposition restriction `INSTRUMENT` & `INSTRUMENT_SUBTYPE` gives the possibility to create a disposition for the specific option chosen by the customer at the merchant's checkout. The customer will be redirected to the SafetyPay payment page immediately.

| Parameter                     | Type                       | Description      | Possible values
| ---                           | ---                        | ---              | ---                  
| `dispositionRestrictions`     | Array                      | The payment restrictions array.
| `key`     | String                      | Value to specify what type of restriction should be applied for the transaction.| `INSTRUMENT`,`INSTRUMENT_SUBTYPE`
| `value`                  | String                     | Value to define the available options for a certain restriction. | `INSTRUMENT`:`paysafecard`, `safetypay`<br>`INSTRUMENT_SUBTYPE`:`cash`,`online`


<a name="createDisposition"></a>
##createDisposition Example
```

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:pscservice">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:createDisposition>
         <urn:username>username_SOAP</urn:username>
         <urn:password>password_SOAP</urn:password>
         <urn:mtid>mtid_soap</urn:mtid>

         <urn:amount>10.00</urn:amount>
         <urn:currency>USD</urn:currency>
         <urn:merchantclientid>customer1</urn:merchantclientid>

         <urn:okUrl>https://www.paysafecard.com/okURL</urn:okUrl>
         <urn:nokUrl>https://www.paysafecard.com/nokURL</urn:nokUrl>
         <urn:pnUrl>https://www.paysafecard.com/pnURL</urn:pnUrl>

         <urn:customerDetail>customer_id</urn:customerDetail>
         <urn:subId>reporting_criteria</urn:subId>
         
        <urn:dispositionRestrictions>
        <urn:key>INSTRUMENT</urn:key>
        <urn:value>safetypay</urn:value>
        <urn:key>INSTRUMENT_SUBTYPE</urn:key>
        <urn:value>cash</urn:value>
        </urn:dispositionRestrictions>

      </urn:createDisposition>
   </soapenv:Body>
</soapenv:Envelope>

```

### New Error Code

Error code "2039" indicates that the value passed in `instrument` is not a valid value.

```   
<ns1:createDispositionResponse>
    <ns1:createDispositionReturn>
        <ns1:mtid>1607092862</ns1:mtid>
        <ns1:resultCode>1</ns1:resultCode>
        <ns1:errorCode>2039</ns1:errorCode>
    </ns1:createDispositionReturn>
</ns1:createDispositionResponse>
```

# Group JSON Payment notification
<a name="payment_notification"></a>
The payment notification is used to notify the business partner independently of the customer’s behaviour after the payment authorization.

This service ensures that payments can be completed before the top-up of the customer’s account and is, therefore, highly recommended in order to avoid incomplete payments.
In case of technical errors (e.g. socket timeout), or application errors (e.g. HTTP 500 response), the payment notification is resubmitted at a regular interval until one of the following criteria is fulfilled:
- The payment notification is successfully delivered (i.e. HTTP 200 response from payment server).
- The maximum number of retry attempts has been reached (currently configured at 5 retries).

A JSON version of the payment notification with all the possible parameters, including the "*payment_instrument*" used, is now available. Example of the body:

```
{
  "timestamp": 1607017210793,
  "eventType": "ASSIGN_CARDS",
  "version": "1",
  "data": {
    "mid": "1100000000",
    "customer": {
        "id": "kfoLkCq3RBIJiJF6sJWBeYA4tnfsCms2"
        },
    "payment_id": "pay_1100000000_XdyBD9FuEJVhpX3hctwJzCB8W1rEzqTo_USD",
    "payment_instrument": "safetypay",
    "payment_instrument_subtype":"cash",
    "card_details": [
      {
        "serial": "1420271325",
        "currency": "USD",
        "amount": 10,
        "type": "00094",
        "country": "XX"
      }
    ]
  }
}
```

**JSON payment notification response objects**

| Parameter                     | Type                       | Description                          
| ---                           | ---                        | ---                                  
| `timestamp`                   | Unix timestamp (in ms)     | The time of the card assign event. 
| `eventType`                   | String                     | The event type that triggered the payment notification. 
| `version`                     | String                     | API version number. 
| `data`                        | Array                      | Contains the data of the transaction. 
| `mid`                         | String                     | The 10-digit Merchant ID.
| `customer`                    | Array                      | Contains the customer data.
| `id`                          | String                     | The unique customer identifier provided by the business partner. 
| `payment_id`                  | String                     | The sub-merchant id. Also knows as reporting criteria. 
| `payment_instrument`          | String                     | The payment method used. <br><br> Possible values: paysafecard or safetypay
| `payment_instrument_subtype`  | String                     | The type of payment option. <br><br> Possible values: cash, online
| `card_details`                | Array                      | Contains the details of the card used for the transaction (up to 10 iterations - max. number of cards that can be used in a single transaction) with the card information.
| `serial`                      | String                     | The serial number that identifies the card.
| `currency`                    | String                     | The currency code of the card in ISO 4217 3-digit format.
| `amount`                      | float                      | The amount used from the card (with 2 decimal numbers).
| `type`                        | String                     | The 5 characters code that identifies the card type.
| `country`                     | Array                      | The country code of the card in ISO 3166-1 2-digit format.


# Group Payment processes
<a name="cash_payment_REST_PP"></a>
## Cash Payment process - REST - intermediary paysafecard redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard and/or SafetyPay

1. [Initiate Payment](#initiate_payment): Send POST request `initiate Payment` 
    * 2.1. If the response gives back http20x, the business partner redirects the customer to the payment panel
    * 2.2. If the response gives back http40x or htp50x, show an error message to the customer
        * Inititate Payment error message: "*Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (businessparter)support.*"

1. Redirection to the payment panel `auth_url`: The customer reaches the paysafecard payment panel
    * 3.1. The customer selects SafetyPay Cash Payment
    * 3.2. The customer is redirected to the SafetyPay hosted payment page
    
1. The customer receives a operation ID code
    * 4.1. The customer has to go to a Point of Collection and complete their payment
    
1. Payment notification delivery: A card will be assigned once the customer completes the payment (transaction status "AUTHORIZED"), paysafecard sends a notification to the `notification_url`

1. `notification_url` handling: Right after the payment notification delivery, the business partner performs the GET request `Retrieve payment details` to check the status of the transaction
    * 6.1. If the GET request `retrieve payment details` returns the status "AUTHORIZED", immediately perform the POST request `capture Payment` 
        * 6.2. If the response to `capture payment` is http20X and the status returned is "SUCCESS", the business partner makes a user account top up accordingly or deliver the goods

<a name="online_payment_REST_PP"></a>
## Online Payment process - REST - intermediary paysafecard redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard and/or SafetyPay

1. [Initiate Payment](#initiate_payment): Send POST request `initiate Payment` 
    * 2.1. If the response gives back http20x, the business partner redirects the customer to the payment panel
    * 2.2. If the response gives back http40x or htp50x, show an error message to the customer
        * Inititate Payment error message: "*Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (businessparter)support.*"

1. Redirection to the payment panel `auth_url`: The customer reaches the paysafecard payment panel
    * 3.1. The customer selects SafetyPay Online Payment
    * 3.2. The customer is redirected to the SafetyPay hosted payment page
    
1. The customer continues with their preferred choice of online payment methods and completes the payment
    
1. Payment notification delivery: A card will be assigned once the customer completes the payment (transaction status "AUTHORIZED"), paysafecard sends a notification to the `notification_url`

1. `notification_url` handling: Right after the payment notification delivery, the business partner performs the GET request `Retrieve payment details` to check the status of the transaction
    * 6.1. If the GET request `retrieve payment details` returns the status "AUTHORIZED", immediately perform the POST request `capture Payment` 
        * 6.2. If the response to `capture payment` is http20X and the status returned is "SUCCESS", the business partner makes a user account top up accordingly or deliver the goods

1. `success_url` handling: The customer may return to the `success_url`. This step is optional. 


<a name="cash_payment_REST_noPP"></a>
## Cash Payment process - REST - immediate SafetyPay redirection
1. The customer selects SafetyPay at the business partner checkout page

1. [Initiate Payment](#initiate_payment): Send POST request `initiate Payment` with "payment_instrument" & "payment_instrument_subtype" parameters set to "safetypay" & "cash": [Initiating a SafetyPay Payment - REST](#restrictions_REST)
    * 2.1. If the response gives back http20x, the business partner redirects the customer to the payment panel
    * 2.2. If the response gives back http40x or htp50x, show an error message to the customer
        * Inititate Payment error message: "*Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (businessparter)support.*"

1. Redirection to the `auth_url`: The customer reaches the SafetyPay Cash Payment Page
    
1. The customer receives a operation ID code
    * 4.1. The customer has to go to a Point of Collection and complete their payment
    
1. Payment notification delivery: A card will be assigned once the customer completes the payment (transaction status "AUTHORIZED"), paysafecard sends a notification to the `notification_url`

1. `notification_url` handling: Right after the payment notification delivery, the business partner performs the GET request `Retrieve payment details` to check the status of the transaction
    * 6.1. If the GET request `retrieve payment details` returns the status "AUTHORIZED", immediately perform the POST request `capture Payment` 
        * 6.2. If the response to `capture payment` is http20X and the status returned is "SUCCESS", the business partner makes a user account top up accordingly or deliver the goods

<a name="online_payment_REST_noPP"></a>
## Online Payment process - REST - immediate SafetyPay redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard and/or SafetyPay

1. [Initiate Payment](#initiate_payment): Send POST request `initiate Payment` with "payment_instrument" & "payment_instrument_subtype" parameters set:[Initiating a SafetyPay Payment - REST](#restrictions_REST)
    * 2.1. If the response gives back http20x, the business partner redirects the customer to the payment panel
    * 2.2. If the response gives back http40x or htp50x, show an error message to the customer
        * Inititate Payment error message: "*Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (businessparter)support.*"

1. Redirection to the `auth_url`: The customer reaches the SafetyPay Online Payment Page
    
1. The customer continues with their preferred choice of online payment methods and completes the payment
    
1. Payment notification delivery: A card will be assigned once the customer completes the payment (transaction status "AUTHORIZED"), paysafecard sends a notification to the `notification_url`

1. `notification_url` handling: Right after the payment notification delivery, the business partner performs the GET request `Retrieve payment details` to check the status of the transaction
    * 6.1. If the GET request `retrieve payment details` returns the status "AUTHORIZED", immediately perform the POST request `capture Payment` 
        * 6.2. If the response to `capture payment` is http20X and the status returned is "SUCCESS", the business partner makes a user account top up accordingly or deliver the goods

1. `success_url` handling: The customer may return to the `success_url`. This step is optional. 

<a name="cash_payment_SOAP_PP"></a>
## Cash Payment process - SOAP - intermediary paysafecard redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard or SafetyPay

1. [create Disposition](#createDisposition): the business partner makes the SOAP request `createDisposition` 
    * 2.1. If the result and error code is `0`, the business partner redirects the customer to the payment panel
    * 2.2. If the result or error code is not `0`, the business partners shows an error message to the customer:

        *"Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (business partner) support."*

1. Redirection to the payment panel with `getCustomerPanel`: The customer reaches the paysafecard payment panel
    * 3.1. The customer selects SafetyPay Cash Payment
    * 3.2. The customer is redirected to the SafetyPay hosted payment page
    
1. The customer receives a operation ID code
    * 4.1. The customer has to go to a Point of Collection to complete the payment
  
1. Payment notification delivery: Since the card is assigned to the transaction (transaction status "S"), paysafecard sends a notification to the `pn_url`

1. `pnUrl` handling: Right after the payment notification delivery, the business partner performs the request `getSerialNumbers` to check the status of the transaction
    * 6.1. If `getSerialNumbers`returns the status "S", immediately perform the `executeDebit` request
        * 6.2. If the response to `executeDebit` is result and error code is `0`, the business partner makes a user account top up accordingly or deliver the goods

<a name="online_payment_SOAP_PP"></a>
## Online Payment process - SOAP - intermediary paysafecard redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard or SafetyPay

1. [create Disposition](#createDisposition): the business partner makes the SOAP request `createDisposition` 
    * 2.1. If the result and error code is `0`, the business partner redirects the customer to the payment panel
    * 2.2. If the result or error code is not `0`, the business partners shows an error message to the customer:

        *"Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (business partner) support."*

1. Redirection to the payment panel with `getCustomerPanel`: The customer reaches the paysafecard payment panel
    * 3.1. The customer selects SafetyPay Online Payment
    * 3.2. The customer is redirected to the SafetyPay hosted payment page
    
1. The customer continues with their preferred choice of online payment methods and completes the payment

1. Payment notification delivery: Since the card is assigned to the transaction (transaction status "S"), paysafecard sends a notification to the `pn_url`

1. `pnUrl` handling: Right after the payment notification delivery, the business partner performs the request `getSerialNumbers` to check the status of the transaction
    * 6.1. If `getSerialNumbers`returns the status "S", immediately perform the `executeDebit` request
        * 6.2. If the response to `executeDebit` is result and error code is `0`, the business partner makes a user account top up accordingly or deliver the goods

1. `okUrl` handling: The customer may return to the `okUrl`. This step is optional. 


<a name="cash_payment_SOAP_noPP"></a>
## Cash Payment process - SOAP - immediate SafetyPay redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard or SafetyPay

1. [create Disposition](#createDisposition): the business partner makes the SOAP request `createDisposition` 
    * 2.1. If the result and error code is `0`, the business partner redirects the customer to the payment panel
    * 2.2. If the result or error code is not `0`, the business partners shows an error message to the customer:

        *"Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (business partner) support."*

1. Redirection to the payment panel with `getCustomerPanel`: The customer reaches the SafetyPay Cash Payment Page
    
1. The customer receives a operation ID code
    * 4.1. The customer has to go to a Point of Collection or pay for the operation ID code with one of the available payment options
  
1. Payment notification delivery: Since the card is assigned to the transaction (transaction status "S"), paysafecard sends a notification to the `pn_url`

1. `pnUrl` handling: Right after the payment notification delivery, the business partner performs the request `getSerialNumbers` to check the status of the transaction
    * 6.1. If `getSerialNumbers`returns the status "S", immediately perform the `executeDebit` request
        * 6.2. If the response to `executeDebit` is result and error code is `0`, the business partner makes a user account top up accordingly or deliver the goods

<a name="online_payment_SOAP_noPP"></a>
## Online Payment process - SOAP - immediate SafetyPay redirection
1. The customer selects the payment method at the business partner checkout page: paysafecard or SafetyPay

1. [create Disposition](#createDisposition): the business partner makes the SOAP request `createDisposition` 
    * 2.1. If the result and error code is `0`, the business partner redirects the customer to the payment panel
    * 2.2. If the result or error code is not `0`, the business partners shows an error message to the customer:

        *"Transaction could not be intitiated due to connection problems. If the problem persists, please contact our (business partner) support."*

1. Redirection to the payment panel with `getCustomerPanel`: : The customer reaches the SafetyPay Online Payment Page
    
1. The customer continues with their preferred choice of online payment methods and completes the payment

1. Payment notification delivery: Since the card is assigned to the transaction (transaction status "S"), paysafecard sends a notification to the `pn_url`

1. `pnUrl` handling: Right after the payment notification delivery, the business partner performs the request `getSerialNumbers` to check the status of the transaction
    * 6.1. If `getSerialNumbers`returns the status "S", immediately perform the `executeDebit` request
        * 6.2. If the response to `executeDebit` is result and error code is `0`, the business partner makes a user account top up accordingly or deliver the goods

1. `okUrl` handling: The customer may return to the `okUrl`. This step is optional. 

<!--!
<a name="customer_flows"></a>

# Group Customer Flows
## Brazil
<!--![BRL_Flow](https://www.paysafecard.com/fileadmin/api/images/BRL_flow.png)
![BRL_Flow](https://pr-www-euc1.eu.paysafecorp.com/fileadmin/api/images/BRL_flow.png)

## Colombia
<!--![COP_Flow](https://www.paysafecard.com/fileadmin/api/images/COP_flow.png)
![COP_Flow](https://pr-www-euc1.eu.paysafecorp.com/fileadmin/api/images/COP_flow.png)

## Chile
<!--![CLP_Flow](https://www.paysafecard.com/fileadmin/api/images/CLP_flow.png) 
![CLP_Flow](https://pr-www-euc1.eu.paysafecorp.com/fileadmin/api/images/CLP_flow.png)

## Mexico
<!--![MXN_Flow](https://www.paysafecard.com/fileadmin/api/images/MXN_flow.png) 
![MXN_Flow](https://pr-www-euc1.eu.paysafecorp.com/fileadmin/api/images/MXN_flow.png)
-->

<a name="bank_ids"></a>
# Group Bank IDs

You can supply one or more Bank IDs in the API request, restricting the customer to only these SafetyPay options.

Sending this parameter without "payment_instrument" does not limit the customer to SafetyPay.


|Payment Instrument Subtype | Country | Bank ID | Bank Name | Bank Provider Name
| --- | --- | --- | --- | ---
| online | BR | 8366 | Banco Itau Boleto | Banco Itau Boleto
| online | BR | 4081 | Banco Itau Robot | Banco Itau
| online | BR | 8183 | Banco do Brasil Robot | Banco do Brasil
| online | BR | 1022 | Banrisul | Banrisul
| online | BR | 8382 | Boleto Flash – PagBrasil | PagBrasil
| online | BR | 8326 | Bradesco PagFacil | Bradesco Pagfacil
| cash   | BR | 8326 | Bradesco PagFacil | Bradesco Pagfacil
| cash   | BR | 8176 | Caixa Econômica Federal | Caixa Econômica Federal
| online | BR | 8439 | PIX | Bradesco PIX
| online | BR | 8042 | Santander Brasil | Santander Brasil
| cash   | CL | 8198 | Acuenta | Walmart Chile
| online | CL | 8296 | Banco BCI One Step | Banco BCI
| cash   | CL | 8194 | Banco Estado | Banco Estado Recaudo Referenciado
| online | CL | 8194 | Banco Estado | Banco Estado Recaudo Referenciado
| online | CL | 8291 | Banco Estado One Step | Banco Estado Boton de Pago
| cash   | CL | 8194 | Caja Vecina | Banco Estado Recaudo Referenciado
| cash   | CL | 8198 | Express de Líder | Walmart Chile
| cash   | CL | 8198 | Líder | Walmart Chile
| online | CL | 8416 | Machpay | Machpay BCI
| online | CL | 8457 | Scotiabank One Step | Scotiabank Chile
| cash   | CL | 8194 | Serviestado | Banco Estado Recaudo Referenciado
| online | CL | 8296 | Tbanc | Banco BCI
| cash   | CL | 8198 | Walmart Chile | Walmart Chile
| cash   | CO | 8323 | Acertemos | Sured
| cash   | CO | 8323 | Apuestas Cúcuta 75 | Sured
| cash   | CO | 8323 | Apuestas Unidas | Sured
| cash   | CO | 8157 | Baloto | Payvalida
| cash   | CO | 8323 | Dimonex | Sured
| cash   | CO | 8224 | Efecty | Efecty
| cash   | CO | 8323 | Gana | Sured
| cash   | CO | 8323 | Gana Gana | Sured
| cash   | CO | 8323 | Jer | Sured
| cash   | CO | 8323 | La Perla | Sured
| cash   | CO | 8231 | MovilRed Colombia | MovilRed Colombia
| online | CO | 4100 | PSE - BANCOOMEVA | PSE
| online | CO | 1099 | PSE - BBVA Colombia | PSE
| online | CO | 8396 | PSE - Bancamía | PSE
| online | CO | 4089 | PSE - Banco AV Villas | PSE
| online | CO | 8185 | PSE - Banco Agrario | PSE
| online | CO | 4090 | PSE - Banco Caja Social | PSE
| online | CO | 4091 | PSE - Banco Colpatria | PSE
| online | CO | 8163 | PSE - Banco Cooperativo Coopcentral | PSE
| online | CO | 4093 | PSE - Banco Davivienda | PSE
| online | CO | 5000 | PSE - Banco Falabella | PSE
| online | CO | 4095 | PSE - Banco GNB Sudameris | PSE
| online | CO | 4096 | PSE - Banco Pichincha COL | PSE
| online | CO | 4097 | PSE - Banco Popular | PSE
| online | CO | 4098 | PSE - Banco ProCredit | PSE
| online | CO | 8332 | PSE - Banco Santander COL | PSE
| online | CO | 4087 | PSE - Banco de Bogota | PSE
| online | CO | 4094 | PSE - Banco de Occidente | PSE
| online | CO | 8389 | PSE - BancoSerfinanza | PSE
| online | CO | 4099 | PSE - Bancolombia | PSE
| online | CO | 4102 | PSE - Citibank Colombia | PSE
| online | CO | 8372 | PSE - Confiar Cooperativa Financiera | PSE
| online | CO | 8503 | PSE - Coofinep | PSE
| online | CO | 8390 | PSE - Cooperativa Financiera de Antioquia | PSE
| online | CO | 8475 | PSE - Dale | PSE
| online | CO | 8371 | PSE - Daviplata | PSE
| online | CO | 8476 | PSE - Giros y Finanzas | PSE
| online | CO | 8477 | PSE - IRIS | PSE
| online | CO | 4092 | PSE - Itau Corpbanca Colombia S.A. | PSE
| online | CO | 8474 | PSE - Movii S.A. | PSE
| online | CO | 8276 | PSE - Nequi | PSE
| online | CO | 8397 | PSE - Rappipay COL | PSE
| cash   | CO | 8323 | Paga Todo Para Todo | Sured
| cash   | CO | 8323 | SuChance | Sured
| cash   | CO | 8323 | SuRed | SuRed
| online | CR | 1021 | Banco Nacional de Costa Rica | Banco Nacional de Costa Rica
| cash   | CR | 1021 | Banco Nacional de Costa Rica | Banco Nacional de Costa Rica
| cash   | EC | 8401 | Almacenes Tía | Red Activa
| cash   | EC | 8458 | Banco Amazonas | Facilito
| cash   | EC | 8458 | Banco Coopnacional | Facilito
| online | EC | 8216 | Banco Guayaquil | Banco Guayaquil
| cash   | EC | 8216 | Banco Guayaquil | Banco Guayaquil
| online | EC | 8066 | Banco Pichincha ECU | Banco Pichincha ECU
| cash   | EC | 8066 | Banco Pichincha ECU | Banco Pichincha ECU
| cash   | EC | 8216 | Banco del Barrio | Banco Guayaquil
| cash   | EC | 8458 | Facilito | Facilito
| cash   | EC | 8401 | Farmacias 911 | Red Activa
| cash   | EC | 8458 | Mastergold | Facilito
| cash   | EC | 8401 | Mi Comisariato | Red Activa
| cash   | EC | 8458 | Orocash   | Facilito
| cash   | EC | 8066 | Pichincha Mi Vecino | Banco Pichincha ECU
| cash   | EC | 8401 | Red Activa | Red Activa
| cash   | GT | 8404 | AKISI PUEDO | Punto Xpress GTM
| cash   | GT | 8404 | Banco de Antigua | Punto Xpress GTM
| cash   | GT | 8404 | Caja de Desarrollo | Punto Xpress GTM
| cash   | GT | 8404 | Fundación Génesis | Punto Xpress GTM
| cash   | MX | 8178 | 7 eleven | OpenPay
| online | MX | 8425 | Afirme Paycash   | Paycash
| cash   | MX | 8425 | Afirme Paycash   | Paycash
| cash   | MX | 8419 | Akala | Paycash
| cash   | MX | 8419 | Alamano | Paycash
| cash   | MX | 8178 | Alsuper | OpenPay
| cash   | MX | 8419 | Atiendas | Paycash
| cash   | MX | 1020 | BBVA Bancomer | BBVA Bancomer
| online | MX | 1020 | BBVA Bancomer | BBVA Bancomer
| cash   | MX | 8186 | Banco Azteca | Banco Azteca
| cash   | MX | 8419 | Banco Forjadores | Paycash
| online | MX | 8395 | Banco Santander WS | Banco Santander
| cash   | MX | 8395 | Banco Santander WS | Banco Santander
| cash   | MX | 1026 | Banorte | Banorte
| cash   | MX | 8419 | Bodega Aurrera | Paycash
| cash   | MX | 8419 | Caja Cerro de la Silla | Paycash
| cash   | MX | 8419 | Caja Solidaria Tamaulipas | Paycash
| cash   | MX | 8419 | Calimax | Paycash
| cash   | MX | 8178 | CircleK | OpenPay
| cash   | MX | 8419 | Comercial Mexicana | Paycash
| cash   | MX | 8419 | DNU | Paycash
| cash   | MX | 8419 | El Gallo de la Laguna | Paycash
| cash   | MX | 8419 | Extra | Paycash
| cash   | MX | 8419 | Farmacia Bazar | Paycash
| cash   | MX | 8178 | Farmacia Benavides | OpenPay
| cash   | MX | 8419 | Farmacia la Más Barata | Paycash
| cash   | MX | 8178 | Farmacias de Ahorro | OpenPay
| cash   | MX | 8419 | Financiera Cefemex | Paycash
| cash   | MX | 8419 | GWV Inversiones | Paycash
| cash   | MX | 8419 | Gestopago | Paycash
| cash   | MX | 8419 | Grupo Blyska | Paycash
| cash   | MX | 8419 | Grupo Pawn | Paycash
| cash   | MX | 8419 | Grupo Águila | Paycash
| cash   | MX | 1052 | HSBC Mexico | HSBC Mexico
| online | MX | 1052 | HSBC Mexico | HSBC Mexico
| cash   | MX | 8419 | Indigo | Paycash
| cash   | MX | 8419 | Kiosko | Paycash
| cash   | MX | 8419 | La Original | Paycash
| cash   | MX | 8419 | Maxilana | Paycash
| cash   | MX | 8419 | Mexamed | Paycash
| cash   | MX | 8419 | Mi Adelanto | Paycash
| cash   | MX | 8419 | Moy Especias | Paycash
| cash   | MX | 8419 | Multi Recargas | Paycash
| cash   | MX | 8419 | One | Paycash
| cash   | MX | 8178 | OpenPay | OpenPay
| cash   | MX | 8419 | Pago Rápido | Paycash
| cash   | MX | 8419 | Paso Seguro Creando Futuro | Paycash
| cash   | MX | 8419 | Paycash   | Paycash
| cash   | MX | 8419 | Peso Fácil | Paycash
| cash   | MX | 8419 | PetroFe | Paycash
| cash   | MX | 8419 | Prenda Mex | Paycash
| cash   | MX | 8419 | Roma | Paycash
| online | MX | 8191 | SPEI MX | OpenPay Online
| online | MX | 8400 | SPEI Robot | OpenPay
| cash   | MX | 8178 | Sam´s Club | OpenPay
| online | MX | 1007 | Scotiabank Mexico | Scotiabank Mexico
| cash   | MX | 1007 | Scotiabank Mexico | Scotiabank Mexico
| cash   | MX | 8419 | Servi Money | Paycash
| cash   | MX | 8419 | Servicios Prendarios del Sureste | Paycash
| cash   | MX | 8419 | Soriana | Paycash
| cash   | MX | 8178 | Super Farmacia | OpenPay
| cash   | MX | 8178 | Super Farmacia Guadalajara | OpenPay
| cash   | MX | 8419 | Super Farmacia Santa Maria | Paycash
| cash   | MX | 8419 | Super Préstamos Premier | Paycash
| cash   | MX | 8419 | Te Creemos | Paycash
| cash   | MX | 8419 | Telecomm | Paycash
| cash   | MX | 8419 | Torcam | Paycash
| cash   | MX | 8419 | Ven Ayuda | Paycash
| cash   | MX | 8178 | Walmart | OpenPay
| cash   | MX | 8178 | Walmart Express | OpenPay
| cash   | PA | 8188 | Western Union Panama | Western Union Panama
| cash   | PE | 8443 | Agente Niubiz | Niubiz
| cash   | PE | 8321 | Agentes Kasnet | Western Union
| online | PE | 1001 | BBVA Perú | BBVA Continental
| cash   | PE | 1001 | BBVA Perú | BBVA Continental
| online | PE | 8391 | BCP Cuotéalo | Banco de Crédito Cuotealo
| cash   | PE | 8320 | Banco Ripley | Western Union
| cash   | PE | 1005 | Banco de Crédito | Banco de Crédito
| online | PE | 1005 | Banco de Crédito | Banco de Crédito
| online | PE | 9999 | BancoDeBanco | BancoDeBanco
| online | PE | 8324 | Caja Arequipa | Caja Arequipa
| cash   | PE | 8324 | Caja Arequipa | Caja Arequipa
| online | PE | 8250 | Caja Huancayo | Caja Huancayo
| cash   | PE | 8250 | Caja Huancayo | Caja Huancayo
| online | PE | 1024 | Caja Tacna | Caja Tacna
| cash   | PE | 1024 | Caja Tacna | Caja Tacna
| online | PE | 1025 | Caja Trujillo | Caja Trujillo
| cash   | PE | 1025 | Caja Trujillo | Caja Trujillo
| cash   | PE | 8442 | Globokas - Kasnet | Globokas - Kasnet
| online | PE | 1011 | Interbank | Interbank
| cash   | PE | 1011 | Interbank | Interbank
| cash   | PE | 8441 | Pichincha PER | Pichincha PER
| online | PE | 8441 | Pichincha PER | Pichincha PER
| cash   | PE | 8444 | Red Digital | Red Digital
| online | PE | 1006 | Scotiabank Perú | Scotiabank Peru
| cash   | PE | 1006 | Scotiabank Perú | Scotiabank Peru
| cash   | PE | 8440 | Tambo+ | Tambo
| cash   | PE | 8320 | Western Union | Western Union
| cash   | SV | 8300 | Airpak | Punto Xpress SLV
| cash   | SV | 8300 | Credicomer | Punto Xpress SLV
| cash   | SV | 8300 | El Gallo Más Gallo | Punto Xpress SLV
| cash   | SV | 8300 | Farmacias Económicas | Punto Xpress SLV
| cash   | SV | 8300 | Fedecrece de RL | Punto Xpress SLV
| cash   | SV | 8300 | Grupo Mega | Punto Xpress SLV
| cash   | SV | 8300 | Integral | Punto Xpress SLV
| cash   | SV | 8300 | Pagos 724 | Punto Xpress SLV
| cash   | SV | 8300 | Punto Xpress SLV | Punto Xpress SLV
| cash   | SV | 8300 | Red de Cooperativas Fedecaces | Punto Xpress SLV
| cash   | SV | 8300 | Super Selectos | Punto Xpress SLV
| cash   | SV | 8300 | Tiendas Galo | Punto Xpress SLV
| cash   | SV | 8300 | Óptima | Punto Xpress SLV








# Data Structures

## TypedObject (object)
+ type: PAYSAFECARD (required, fixed) - Type of the product, must be set to PAYSAFECARD.

## PaymentRequest (TypedObject)
+ amount: 10.00 (number, required) - Payment amount, precision must be 2 digits after the colon.
+ currency: USD (required) - ISO 4217 - 3 letter ISO currency code.
+ redirect (object) 
    + `success_url`: https://notification.com/{payment_id} (required) - URLs to redirect after successful or failed authorization. The placeholder {payment_id} in the URL is replaced with the actual ID of this payment.
    + `failure_url`: https://notification.com/{payment_id} (required) - URLs to redirect after customer clicked on cancel. The placeholder {payment_id} in the URL is replaced with the actual ID of this payment.
+ `notification_url`: https://notification.com/{payment_id} (required)- Notification URL we will contact after the authorization has been successfully completed. The placeholder {payment_id} in the URL is replaced with the actual ID of this payment.
+ customer (object) 
    + id: merchantclientid5HzDvoZSodKDJ7X7VQKrtestAutomation (required) - Only the id is mandatory. It´s value uniquely identifies the customer and is provided by you. If any personal data e.g. customer´s user name, email address, is used here, it has to be encrypted or hashed for security reasons.  
    + min_age: 18 (optional) - Valid for my paysafecard payments. For additional information about my paysafecard, please see the section "my paysafecard". Restricts payments to my paysafecard customers only, who are equal to or older than the specified age. Please note: This means that it is required that the customer has a registered my paysafecard account to make the payment. 
    + kyc_level: SIMPLE (optional) - Valid values SIMPLE or FULL. These values refer to the KYC level of the customer's my paysafecard account. Depending on the country, my paysafecard accounts are offered with SIMPLE and/or FULL customer identification. 
    + country_restriction: AT (optional) - ISO 3166-1 alpha-2 two-letter country code used to restrict payments to residents of a particular country.
+ restrictions (object)
    + payment_instrument: giftcard (optional) - The Payment instrument gives the possibility to initiate the payment for the specific option choosen at the checkout page. Possible values: "*paysafecard*" **or** "*giftcard*".
    + payment_instrument_subtype: openbuckscard (optional) -  If "giftcard" was used for the `payment_instrument`, the payment can be initiated for a specific Giftcard option by defining a subtype. Possible values: "*cvspharmacy*" **or** "*dollargeneral*" **or** "*openbuckscard*".
+ submerchant_id: 1 (optional) - Also called ‘reporting criteria’, offers the possibility to classify sub-merchants. Agreement with paysafecard needed - not agreed values lead to a failed payment. max. 8 digits in alpha numeric code
+ shop_id: `shop1` (optional) - Identification of the shop which is the originator of the request. This is most likely used by payment service providers who act as a proxy for other payment methods as well.