FORMAT: 1A
HOST: https://api.paysafecard.com/v1

# paysafecard Store Locator API

# Technical Integration
This section provides a technical introduction to the paysafecard Store Locator REST API.

## About the API
The paysafecard Store Locator API provides a list and details of payment points around a geographic location.

The payment points can be filtered by various criteria and the results are shown in JSON format.

<br><br>
The paysafecard Store Locator REST API follows <a href="http://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank">*RESTful*</a> design principles making it easy to understand and integrate the API.
Representational State Transfer (REST) is a software architecture style, consisting of guidelines for creating scalable web services.

RESTful systems typically communicate over the Hypertext Transfer Protocol with the same HTTP verbs (GET, POST, PUT, DELETE, etc.) used by web browsers to retrieve web pages and send data to remote servers.

It also facilitates solid and universally accepted foundations like [*http basic authentication*](http://en.wikipedia.org/wiki/Basic_access_authentication), [*http verbs*](http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods), [*JSON*](http://en.wikipedia.org/wiki/JSON) and [*CORS*](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

## Versioning
Every time there is backwards-incompatible change to the API, a new major version will be released. This major version is part of the URL path.
The current major version is *v1*. Unless informed by our technical support department that we are dropping support for a particular API version, you do not need to switch API versions.

## Prerequisites
A connection to the paysafecard Store Locator API is successful if the following prerequisites are fulfilled:
- API key for request authentication provided by paysafecard.
- Authorization of the server IP address in the production environment (if a 403 error is received when trying to access the service, it is likely that the IP address is not yet allowed to access).
- Content-type: Please make sure that the content type in the HTTP header, when submitting requests, is set to **Content-Type: application/json**
- Character encoding needs to be in UTF-8

## API key authentication
Every request to the paysafecard API is authenticated using an API key.
- The value of the **API key needs to be base64 encoded** when transmitted in the HTTP header!
- Set the key as the username. [*HTTP basic authentication*](http://en.wikipedia.org/wiki/Basic_access_authentication)
- Your API key may only be used from your backend systems.
- **Please note:** Your API key must be kept secured - never expose the API key to anybody!

Below is an example of how the API key is supposed to be set.

```
Authorization: Basic cHNjX0R4dThqSnI1LVdPYXhLWnpjOXdyMUtNLXd1Y3dZMXg=
```

## Test Environment and Endpoints
Every new business partner needs to first integrate the API in the test environment.
Once the integration is finished, a UAT(User Acceptance Test) needs to be done in order to ensure a seemless integration flow.

- The endpoint for the *test environment* is: https://apitest.paysafecard.com/v1/stores/
- The endpoint for the *production environment* is: https://api.paysafecard.com/v1/stores/

## Interface Guidelines
The paysafecard Store Locator API must be implemented accordingly to the interface guidelines provided by the paysafecard integration team with the test data package and the instructions in this document.

## Store Locator API Request [/stores?lat={lat}8&long={long}&radius={radius}&productAction={productAction}&limit={limit}&offset={offset}&sortOrder={sortOrder}&product={product}]

### locate stores [GET]

+ Parameter

    + lat: `48.3705878` (big decimal, optional) - Latitudinal search position (default to null). <br></br>
    + long: `10.8987651` (big decimal, optional) - Longitudinal search position (default to null). <br></br>
    + radius: `20` (big decimal, optional) - Radius in kilometers around lat/long to search for stores (default to null). <br></br>
    + productAction: `Classic` (String, optional) - For which product sub type should the search apply to (default to null). <br></br>
    + limit: `2` (String, optional) - Number of results to return (default to null).  <br></br>
    + offset: `1` (String, optional) - Start position in the search results, used for pagination (default to null). <br></br>
    + sortOrder: `ASC` (String, optional) - Sort order (default to null). <br></br>
    + product: `paysafecard` (String, optional) - For which product should the search apply to (default to null). <br></br>
    
+ Request

    + Headers
            
            Authorization: Basic cHNjX0JUMlpXRWVjZ01BOXZiU1RFQS0yd2tBQVM2aHVzbjg=
            Content-Type: application/json

+ Response 200 (application/json)

        [
        {
        "posId": 3820802,
        "name": "Del Internet  Callshop",
        "address": "Schmiedberg 11",
        "latitude": 48.3710119,
        "longitude": 10.8992594,
        "postalCode": "86152",
        "city": "Augsburg",
        "cheatSheetURL": null,
        "distributorId": 277555954,
        "country": "DEU",
        "posTypeLogo": null,
        "productType": "paysafecard",
        "media": "EVoucher",
        "productLogo": "https://www.paysafecard.com/include/posicon/",
        "specialImage": null,
        "specialText": "",
        "cheatSheetText": null,
        "recommended": "false",
        "distanceFromOrigin": 60.0,
        "storeFeedbacks": [],
        "directload": false
        },
        {
        "posId": 3820798,
        "name": "Delinternetcafe1",
        "address": "Schmiedberg 11",
        "latitude": 48.3710119,
        "longitude": 10.8992594,
        "postalCode": "86152",
        "city": "Augsburg",
        "cheatSheetURL": null,
        "distributorId": 277555954,
        "country": "DEU",
        "posTypeLogo": null,
        "productType": "paysafecard",
        "media": "EVoucher",
        "productLogo": "https://www.paysafecard.com/include/posicon/",
        "specialImage": null,
        "specialText": "",
        "cheatSheetText": null,
        "recommended": "false",
        "distanceFromOrigin": 60.0,
        "storeFeedbacks": [],
        "directload": false
        }
        ]


# Group Store Locator API Response Parameters
| Parameter             | Type      | Example                                           | Description                          
| ---                   | ---       | ---                                               | ---                                  
| `posId`               | number    | 3820802                                           | 
| `name`                | string    | Del Internet  Callshop                            | 
| `address`             | string    | Schmiedberg 11                                    |
| `latitude`            | number    | 48.3710119                                        |
| `longitude`           | number    | 10.8992594                                        |
| `postalCode`          | string    | 86152                                             |
| `city`                | string    | Augsburg                                          |
| `cheatSheetURL`       | string    | https://cheatsheet.com                            |
| `distributorId`       | number    | 277555954                                         |
| `country`             | string    | DEU                                               |
| `posTypeLogo`         | string    | null                                              |
| `productType`         | string    | paysafecard                                       |
| `media`               | string    | EVoucher                                          |
| `productLogo`         | string    | https://www.paysafecard.com/include/posicon/      |
| `specialImage`        | string    | null                                              |
| `specialText`         | string    | ""                                                |
| `cheatSheetText`      | string    | null                                              |
| `recommended`         | boolean   | false                                             |
| `distanceFromOrigin`  | number    | 60.00                                             |
| `storeFeedbacks`      | arrayd    | []                                                |
| `directload`          | false     | -                                                 |

# Group Store Locator API Error Codes
|Code                           |Number (optional)  |HTTP Status    |Description          |
|---                            |---                |---            |---                  |
|`general_technical_error`      |10007              |500            |General technical error.|
|`invalid_api_key`              |10008              |401            |Authentication failed due to missing or invalid API key. Your key needs to be set to the HTTP auth username.|
|`invalid_request_parameter`    |10028              |400            |One of the request parameters failed validation. The `message` and `param` fields contain more detailed information.|